services:
  node:
    build: .
    container_name: review
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0.32
    container_name: review_db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
